[project]
name = "ra_utils"
dynamic = ["version"]
requires-python = ">=3.9"
description = "ra_utils is a python package used for Sharp-van-der-Heijde score prediction. Most notably it contains the Chronological Contrastive loss function for the MIDL2026 conference."
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Clemens Watzenboeck", email = "clemens.watzenboeck@meduniwien.ac.at"},
    { name = "Paul Weiser"},
    { name = "Thomas Deimel"},        
    { name = "Center for Imaging Research; Medical University of Vienna" }
]
classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Healthcare Industry",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Image Recognition",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
]
keywords = [
    "deep learning",
    "medical image analysis",
]
dependencies = [
    "nbstripout",
    "torch",
    "torchvision",
    "torchmetrics",
    "monai",
    "pydicom",
    "tqdm",
    "dicom2nifti",
    "scipy",
    "numpy",
    "scikit-learn",
    "scikit-image",
    "SimpleITK",
    "pandas",
    "graphviz",
    "requests",
    "nibabel",
    "matplotlib",
    "seaborn",
    "imagecodecs",
    "yacs",
    "einops",
    "pytest",
    "imutils",  # for code of thomas
    #"importlib-metadata"
    "ipython",
    "jupyter", 
    "ipykernel",
    "mlflow",
    "pingouin",
    # "landmarker",
    "optuna", 
#    "rpy2", 
    "openpyxl", 
    "pyqt5",
    "napari>=0.4.3",
    "magicgui>=0.2.5",           
    "dask-image",                 
    "numexpr>=2.8.4",
    #
    #
    "transformers @ git+https://github.com/huggingface/transformers",
    "huggingface_hub",
    "fiftyone",
    "python-dotenv"
]

[project.scripts]
ra_utils__print_package_infos = "ra_utils.tools.print_package_info:main"
ra_utils__visualize_latentspace = "ra_utils.visualization.interactive.ra_model:main"
ra_utils__sum_and_plot_SvH = "ra_utils.evaluation.plot_and_save_true_vs_predicted_summed_scores:main"
ra_utils__compute_progression_classification_metrics = "ra_utils.evaluation.save_progression_classification_metrics:main"
ra_utils__train = "ra_utils.ra_utils.training.scores_SHS.train:main"


[project.optional-dependencies]
dev = [
    "black",
    "ruff",
    "pre-commit"
]
rpackages = [
  # these can’t be installed via pip, but you can document that
  # users should do:
  #   conda install -c conda-forge r-lme4 r-matrix r-reformulas r-psych r-irr
  # or the apt/yum equivalent for Matrix, lme4, etc.
]


[build-system]
requires = ["setuptools>=67.8.0", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["ra_utils"]
exclude = [
    "docs",
    "documentation",
    "logs",
    "notebooks",
    "references",
    "singularity",
    "slurm",
    "tests",
    "tutorials",
    "data",
    "features",
    "inference",
    "networks",
    "training",
    "utils",
    "visualization", 
]

[tool.setuptools_scm]
write_to = "ra_utils/_version.py"
local_scheme = "node-and-date"

[tool.setuptools.package-data]
"ra_utils.resources.patch_extraction" = ["*.json"]
"ra_utils.resources.scores_metadata" = ["*.json", "*.yml"]
