program: finetuning.py
name: finetuning_tessl
method: grid
metric:
  goal: minimize
  name: train_total_loss
epochs: 50
device: 'cuda'
system: 'msc'
data_path: '/msc/home/ijanic99/data/2024_ISPY2_multimodal/ISPY2_Parametric_maps/'
model_path: '/msc/home/ijanic99/TemporalLoss/progressionlearning/results/pretraining_sep_all_timepoitns/'
save_path: '/msc/home/ijanic99/TemporalLoss/progressionlearning/results/pretraining_tessl_sep_all_timepoitns/finetuning/'
timepoints: ['T0', 'T1', 'T2', 'T3']
batch_size: 16
val_batch_size: 16
filters: [16,32,64,128,256,32]
parameters:
  num_heads:  
    values: [1]
  gamma:
    values: [2]
  lr_pretrained:
    values: [0.0001]
  lr:
    values: [0.0001]
  mode:
    values: ['all', 'sup_temp', 'sup', 'temp']