#!/bin/sh
#SBATCH --cpus-per-task=32
#SBATCH --mem=256G
#SBATCH -o /msc/home/cwatze93/logs/singularity_build.o%A.txt
#SBATCH --time=0-02:00:00
set -e
set -x 

singularity build --fakeroot ~/container/FRESH_ra_utils.sif ~/code/RA/ra_utils/singularity/build_ra_utils_container_filled.def
rm /msc/home/cwatze93/container/ra_utils.sif
mv ~/container/FRESH_ra_utils.sif   /msc/home/cwatze93/container/ra_utils.sif

